name: playx_3d_scene
description: Plugin for rendering interactive 3D models based on Google filament natively on Android. 
  With the ability of controlling environment skybox, light, camera, ground and more.
version: 0.1.0
homepage: https://sourcya.com/
repository: https://github.com/playx-flutter/playx-3d-scene
issue_tracker: https://github.com/playx-flutter/playx-3d-scene/issues
screenshots:
  - description: 'This screenshot shows 3d model with HDR environment.'
    path: screenshots/screenshot1.jpg
  - description: 'This screenshot shows different shapes with HDR environment'
    path: screenshots/screenshot2.jpg

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.sourcya.playx_3d_scene
        pluginClass: Playx3dScenePlugin



